### PR TITLE
[SRE-127] - Adds cardano-rosetta to Hydra

### PR DESCRIPTION
**Pull request by craigem**

### CODE REVIEW

**Review by sevanspowell — APPROVED** [review]

**Comment by rvl** [comment]
Have you checked that they want hydra and bors?

**Comment by craigem** [comment]
> Have you checked that they want hydra and bors?

Hey @rvl :-)

They did last time it was discussed. Has that changed?

**Comment by rvl** [comment]
I'm just checking because that project seems like it's docker-only. And also bors usually gets in the way unless there are lots of PRs being merged.

**Comment by craigem** [comment]
All fair questions too. We need to cherry pick `cardano-rosetta-server` out of this. So `bors` may well be dropped but we still want that component to go through Hydra at least, as I presently understand the work,

**Pull request merged**
